// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNvTwCRjnaHnfzC6ji_UIPb2xYGbjJVjM',
    appId: '1:135189728647:web:d8b376be21876e063e5722',
    messagingSenderId: '135189728647',
    projectId: 'flutter-login-page-d71b0',
    authDomain: 'flutter-login-page-d71b0.firebaseapp.com',
    storageBucket: 'flutter-login-page-d71b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOIANOuWr0wOcBncG55N4GlQoyuZdzeAs',
    appId: '1:135189728647:android:2f08476b03c776a83e5722',
    messagingSenderId: '135189728647',
    projectId: 'flutter-login-page-d71b0',
    storageBucket: 'flutter-login-page-d71b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIDkSD9pZUoYk3o9YU99XiSQ8eJQfcMI',
    appId: '1:135189728647:ios:3600987bae26728d3e5722',
    messagingSenderId: '135189728647',
    projectId: 'flutter-login-page-d71b0',
    storageBucket: 'flutter-login-page-d71b0.appspot.com',
    iosBundleId: 'com.example.flutterDersleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaIDkSD9pZUoYk3o9YU99XiSQ8eJQfcMI',
    appId: '1:135189728647:ios:3600987bae26728d3e5722',
    messagingSenderId: '135189728647',
    projectId: 'flutter-login-page-d71b0',
    storageBucket: 'flutter-login-page-d71b0.appspot.com',
    iosBundleId: 'com.example.flutterDersleri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNvTwCRjnaHnfzC6ji_UIPb2xYGbjJVjM',
    appId: '1:135189728647:web:6d6443056fb96be93e5722',
    messagingSenderId: '135189728647',
    projectId: 'flutter-login-page-d71b0',
    authDomain: 'flutter-login-page-d71b0.firebaseapp.com',
    storageBucket: 'flutter-login-page-d71b0.appspot.com',
  );
}
