// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxhfM5evBtOFZxia47UoHDtL848cXvBtk',
    appId: '1:68984628362:web:9b07d59b6d65272f887973',
    messagingSenderId: '68984628362',
    projectId: 'word-sparkle',
    authDomain: 'word-sparkle.firebaseapp.com',
    storageBucket: 'word-sparkle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9m7dxuLsn_wUhzV-AvkV53urzD-HsMO4',
    appId: '1:68984628362:ios:c54a43ad873d4b33887973',
    messagingSenderId: '68984628362',
    projectId: 'word-sparkle',
    storageBucket: 'word-sparkle.appspot.com',
    iosBundleId: 'com.example.wordSparkle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9m7dxuLsn_wUhzV-AvkV53urzD-HsMO4',
    appId: '1:68984628362:ios:c54a43ad873d4b33887973',
    messagingSenderId: '68984628362',
    projectId: 'word-sparkle',
    storageBucket: 'word-sparkle.appspot.com',
    iosBundleId: 'com.example.wordSparkle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxhfM5evBtOFZxia47UoHDtL848cXvBtk',
    appId: '1:68984628362:web:36431911e9159078887973',
    messagingSenderId: '68984628362',
    projectId: 'word-sparkle',
    authDomain: 'word-sparkle.firebaseapp.com',
    storageBucket: 'word-sparkle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvXrK0QmbBXVD7wz_r2X-RIgiqF2uaadE',
    appId: '1:68984628362:android:14df98e933ba00f9887973',
    messagingSenderId: '68984628362',
    projectId: 'word-sparkle',
    storageBucket: 'word-sparkle.appspot.com',
  );

}