// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEHT6bXCpgCnTnFH8VVPV1TIQ0cV0K6aA',
    appId: '1:576230739821:web:ea526b9e87d58d5264d464',
    messagingSenderId: '576230739821',
    projectId: 'last-project-42715',
    authDomain: 'last-project-42715.firebaseapp.com',
    storageBucket: 'last-project-42715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-pq2YO2pEoxy3eizKoh_OvW4_9J2bS8',
    appId: '1:576230739821:android:09f4167bf0112f3a64d464',
    messagingSenderId: '576230739821',
    projectId: 'last-project-42715',
    storageBucket: 'last-project-42715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNBncn6sRaONQHfB1IFb2yyWnsotZG5Hs',
    appId: '1:576230739821:ios:3b01924d80f5f91d64d464',
    messagingSenderId: '576230739821',
    projectId: 'last-project-42715',
    storageBucket: 'last-project-42715.appspot.com',
    iosBundleId: 'com.example.lastProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNBncn6sRaONQHfB1IFb2yyWnsotZG5Hs',
    appId: '1:576230739821:ios:3b01924d80f5f91d64d464',
    messagingSenderId: '576230739821',
    projectId: 'last-project-42715',
    storageBucket: 'last-project-42715.appspot.com',
    iosBundleId: 'com.example.lastProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEHT6bXCpgCnTnFH8VVPV1TIQ0cV0K6aA',
    appId: '1:576230739821:web:8235ef4c6eaac8e764d464',
    messagingSenderId: '576230739821',
    projectId: 'last-project-42715',
    authDomain: 'last-project-42715.firebaseapp.com',
    storageBucket: 'last-project-42715.appspot.com',
  );
}
